from django.urls import  path

from . import views

app_name = 'contract'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('contract_list/', views.contract_list, name = 'contract_list'),
    path('contract_list/search', views.contract_list_search, name='contract_list_search'),
    path('contract_list/add_form/', views.contract_add_form, name = 'contract_add_form'),
    path('contract_list/add_form/add', views.contract_add, name = 'contract_add'),
    path('contract_list_<str:filter>/', views.contract_list_filter, name='contract_list_filter'),
    path('contract_list/<str:contract_code>/', views.contract, name = 'contract'),
    path('contract_list/<str:contract_code>/print', views.contract_print, name = 'contract_print'),
    path('contract_list/<str:contract_code>/save/', views.contract_save, name = 'contract_save'),
    path('employee_list/', views.employee_list, name = 'employee_list'),
    path('employee_list/add_form/', views.employee_add_form, name = 'employee_add_form'),
    path('employee_list/add_form/add', views.employee_add, name = 'employee_add'),
    path('employee_list/<str:employee_code>/', views.employee, name = 'employee'),
    path('employee_list/<str:employee_code>/save/', views.employee_save, name = 'employee_save'),
    path('executor_list/', views.executor_list, name='executor_list'),
    path('executor_list/add_form/', views.executor_add_form, name='executor_add_form'),
    path('executor_list/add_form/add', views.executor_add, name='executor_add'),
    path('executor_list/<str:executor_code>/', views.executor, name='executor'),
    path('executor_list/<str:executor_code>/save/', views.executor_save, name='executor_save'),
    path('customer_list/', views.customer_list, name='customer_list'),
    path('customer_list/add_form/', views.customer_add_form, name='customer_add_form'),
    path('customer_list/add_form/add', views.customer_add, name='customer_add'),
    path('customer_list/<str:customer_code>/', views.customer, name='customer'),
    path('customer_list/<str:customer_code>/save/', views.customer_save, name='customer_save'),
    path('work_list_main/', views.work_list_main, name='work_list_main'),
    path('work_list/search', views.work_list_search, name='work_list_search'),
    path('work_list_main/<str:filter>', views.work_list_filter, name='work_list_filter'),
    path('work_list_main/save_default<str:work_code>/', views.work_list_save_default, name='work_list_save_default'),
    path('work_list_main/save_actual<str:work_code>/', views.work_list_save_actual, name='work_list_save_actual'),
    path('work_list_main/save_payment<str:work_code>/', views.work_list_save_payment, name='work_list_save_payment'),
    path('work_list_main/work_add_form/', views.work_add_form, name='work_add_form'),
    path('work_list_main/work_add_form/add', views.work_add, name='work_add'),
    path('work_list_main/<str:work_code>/', views.work, name='work'),
    path('work_list_main/<str:work_code>/save/', views.work_save, name='work_save'),
    path('bill_list_<str:filter>/', views.bill_list, name='bill_list'),
    path('bill_list/add_form_<str:filter>/', views.bill_add_form, name='bill_add_form'),
    path('bill_list/add_form/add<str:filter>', views.bill_add, name='bill_add'),
    path('bill_list/<str:bill_code>/', views.bill, name='bill'),
    path('bill_list/<str:bill_code>/save/', views.bill_save, name='bill_save'),
    path('act_list_<str:filter>/', views.act_list, name='act_list'),
    path('act_list/add_form_<str:filter>/', views.act_add_form, name='act_add_form'),
    path('act_list/add_form/add<str:filter>', views.act_add, name='act_add'),
    path('act_list/<str:act_code>/', views.act, name='act'),
    path('act_list/<str:act_code>/save/', views.act_save, name='act_save'),
]