# Generated by Django 3.1.7 on 2021-05-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('contract_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код договора')),
                ('contract_number', models.CharField(max_length=20, verbose_name='Номер договора')),
                ('description', models.TextField(verbose_name='Наименование')),
                ('contract_date', models.DateTimeField(verbose_name='Дата договора')),
                ('contract_end_date', models.DateTimeField(null=True, verbose_name='Дата окончания договора')),
                ('payment', models.BooleanField(null=True, verbose_name='Оплата по договору')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код заказчика')),
                ('organization_name', models.CharField(max_length=250, verbose_name='Название организации')),
                ('post_index', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('payment_account', models.CharField(max_length=20, verbose_name='Рассчетный счёт')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('сorrespondent_bill', models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт')),
                ('ogrn', models.CharField(blank=True, max_length=13, verbose_name='ОГРН')),
                ('fio', models.CharField(blank=True, max_length=100, verbose_name='Имя и инициалы')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код сотрудника')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Executors',
            fields=[
                ('executor_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код исполнителя')),
                ('organization_name', models.CharField(max_length=250, verbose_name='Название организации')),
                ('post_index', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('payment_account', models.CharField(max_length=20, verbose_name='Рассчетный счёт')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('сorrespondent_bill', models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт')),
                ('fio', models.CharField(blank=True, max_length=100, verbose_name='Имя и инициалы')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('work_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код работы')),
                ('type_of_work', models.CharField(max_length=250, verbose_name='Вид работы')),
                ('description', models.TextField(verbose_name='Наименование')),
                ('work_start_date', models.DateTimeField(null=True, verbose_name='Дата начала работы')),
                ('work_end_date', models.DateTimeField(null=True, verbose_name='Дата завершения работы')),
                ('contract_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.contracts')),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.employees')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Estimates',
            fields=[
                ('estimate_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код сметы')),
                ('estimates_number', models.CharField(max_length=20, verbose_name='Номер сметы')),
                ('contract_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.contracts')),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
            },
        ),
        migrations.AddField(
            model_name='contracts',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.customers'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.executors'),
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код счета')),
                ('bill_number', models.CharField(max_length=5, verbose_name='Номер счета')),
                ('bill_date', models.DateTimeField(verbose_name='Дата счета')),
                ('payment', models.BooleanField(null=True, verbose_name='Оплата по счету')),
                ('contract_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.contracts')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Acts',
            fields=[
                ('act_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код акта')),
                ('act_number', models.CharField(max_length=5, verbose_name='Номер акта')),
                ('act_date', models.DateTimeField(verbose_name='Дата акта')),
                ('contract_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.contracts')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
            },
        ),
    ]
