# Generated by Django 3.1.7 on 2021-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='act_date',
            field=models.DateField(verbose_name='Дата акта'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='bill_date',
            field=models.DateField(verbose_name='Дата счета'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_date',
            field=models.DateField(verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_end_date',
            field=models.DateField(null=True, verbose_name='Дата окончания договора'),
        ),
        migrations.AlterField(
            model_name='works',
            name='work_end_date',
            field=models.DateField(null=True, verbose_name='Дата завершения работы'),
        ),
        migrations.AlterField(
            model_name='works',
            name='work_start_date',
            field=models.DateField(null=True, verbose_name='Дата начала работы'),
        ),
    ]
