# Generated by Django 3.1.7 on 2021-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210513_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='fio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия, имя и отчество'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='fio',
            field=models.CharField(max_length=100, verbose_name='Фамилия, имя и отчество'),
        ),
        migrations.AlterField(
            model_name='executors',
            name='fio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия, имя и отчество'),
        ),
    ]
