# Generated by Django 3.1.7 on 2021-05-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210513_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='type_of_work',
            field=models.CharField(max_length=250, null=True, verbose_name='Вид работы'),
        ),
    ]
