# Generated by Django 3.1.7 on 2021-05-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20210520_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='executors',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, verbose_name='ОГРН'),
        ),
    ]
