# Generated by Django 3.1.7 on 2021-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_executors_ogrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executors',
            name='address',
            field=models.CharField(default=2, max_length=100, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
