# Generated by Django 3.1.7 on 2021-05-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20210527_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='employee_code',
        ),
        migrations.AddField(
            model_name='works',
            name='employee_code',
            field=models.ManyToManyField(to='document.Employees'),
        ),
    ]
