# Generated by Django 3.1.7 on 2021-05-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20210528_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='work_status',
            field=models.BooleanField(default=False, null=True, verbose_name='Статус выполнения работы'),
        ),
        migrations.AlterField(
            model_name='works',
            name='description',
            field=models.TextField(null=True, verbose_name='Наименование'),
        ),
    ]
