# Generated by Django 3.1.7 on 2021-06-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20210529_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimates',
            name='hide',
        ),
        migrations.AddField(
            model_name='employees',
            name='hide',
            field=models.BooleanField(default=False, null=True, verbose_name='Скрыть сотрудника'),
        ),
    ]
